# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/boletos_aereos_db
spring.datasource.username=postgres
spring.datasource.password=Josue2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true